# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Listener' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'NVActivityIndicatorView'

  # Pods for Listener

  target 'ListenerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListenerUITests' do
    # Pods for testing
  end

end
